stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} test.env
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
